version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/template"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "â¬†ï¸"
    pull-request-branch-name:
      separator: "-"
    pull-request-title:
      prefix: "ğŸ”€"
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    file-type: "requirements"

  - package-ecosystem: "pip"
    directory: "/template"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "â¬†ï¸"
    pull-request-branch-name:
      separator: "-"
    pull-request-title:
      prefix: "ğŸ”€"
    groups:
      dev-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    file-type: "requirements-dev"
